---
colours:  #colours to be displayed
  - 'green'
  - 'blue'
  - 'yellow'
  - 'pink'
imagesCount: 0 #amount of images to be displayed

settings:
  includeColours: true  #use colours
  includeImages: false  #use images
  mode: 2               #0: random colours, side matches side. 1: in order, skips 1/2 screen  2: in order only whole screens. 3: in order only half screens
  screens: 6            #the amount of screens that need to be set
  delay: 5              #the delay between slide showss